### ISSUE TITLE
Replace Data Quality and SLA components with DataQoS component

### ISSUE THREAD

**Issue by kyyberi** [Open-Data-Product-Initiative/v3.0#66]
### Describe the solution you'd like ###

I am suggesting we adopt the DataQoS concept in ODPS, https://open-data-product-initiative.github.io/DataQoS-as-code 
The example is not complete so it has to be developed. That Component would make Data Quality and SLA objects obsolete, yet enables the same outcome and use cases. 

DataQoS can be used only for Data quality if SLA is not relevant. Also the other way around, it can be used only for SLA if DQ is not needed. 

This would simplify the ODPS and also bring the Everything as Code aspect into the ODPS. 

### Can you submit a pull request? ###

Yes, I can work in this and build a pull requests. It will take a moment but yes. 

### ---- Leave intact! Approval of Contributor Agreement ----- ### 
By submitting issue you approve the Contributor Agreement, https://governance.opendataproducts.org/v1/contributions/contributor-agreement

**Comment by kyyberi** [comment]
@niilahti let me know what you think

**Comment by niilahti** [comment]
I support the change; the current quality model is not good enough and does not promote the as Code aspect.

**Comment by kyyberi** [comment]
Decided to keep the SLA and Data quality still separate instead of merging all together. Perhaps in the future the two are combined. Also decided that both SLA and Data quality structure should be the same to ease the adoption.

**Comment by kyyberi** [comment]
the changes have been implemented to Dev version. Closing.
